name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  unit-test:
    name: Perform Unit Testing
  #    needs: [ lint ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
  
      - name: Run tests
        run: ./gradlew test
        
      - name: Upload test report
        uses: asadmansr/android-test-report-action@v1.2.0
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/
