name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      
      - name: Generate Keystore file from Github Secrets
        run: |
          echo "$KEYSTORE" > ./keystore/keystore.b64
          base64 -d -i ./keystore/keystore.b64 > ./android.keystore
        env:
          KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  unit-test:
    name: Perform Unit Testing
  #    needs: [ lint ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
  
      - name: Run tests
        run: ./gradlew test
        
      - name: Upload test report
        uses: asadmansr/android-test-report-action@v1.2.0
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/

  instrumentation-test:
    name: Perform Instrumentation Testing
    needs: [ unit-test ]
    runs-on: macos-latest # MacOS runs faster
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Gradle v8.0.0 requires java JDK v17
      - name: Set up Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2 # 3rd party tool
        with:
          api-level: 34
          script: ./gradlew connectedCheck
