name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  env-set:
    runs-on: ubuntu-20.04
    steps:
      - name: Use variables
        run: |
          echo "KEYSTORE_PASSWORD variable : $KEYSTORE_PASSWORD"
          echo "KEY_ALIAS variable : $KEY_ALIAS"
          echo "KEY_PASSWORD variable : $KEY_PASSWORD"
        env:
          KEYSTORE_PASSWORD: ${{ vars.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
          KEY_PASSWORD: ${{ vars.KEY_PASSWORD }}
        
  build:
    runs-on: ubuntu-20.04
    needs: [ env-set ]
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Use variables
        run: |
          echo "KEYSTORE_PASSWORD variable : $KEYSTORE_PASSWORD"
          echo "KEY_ALIAS variable : $KEY_ALIAS"
          echo "KEY_PASSWORD variable : $KEY_PASSWORD"
        env:
          KEYSTORE_PASSWORD: ${{ vars.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
          KEY_PASSWORD: ${{ vars.KEY_PASSWORD }}
      - name: Generate Keystore file from Github Secrets
        run: |
          echo $KEYSTORE | base64 -di > ./android.keystore
        env:
          KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  unit-test:
    name: Perform Unit Testing
    needs: [ env-set ]
    #    needs: [ lint ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: asadmansr/android-test-report-action@v1.2.0
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/

  instrumentation-test:
    name: Perform Instrumentation Testing
    needs: [ unit-test ]
    runs-on: macos-latest # MacOS runs faster
    strategy:
      matrix:
        api-level: [ 34 ]
        target: [ default, google_apis ]
        arch: [ x86_64, x86 ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Use variables
        run: |
          echo "KEYSTORE_PASSWORD variable : $KEYSTORE_PASSWORD"
          echo "KEY_ALIAS variable : $KEY_ALIAS"
          echo "KEY_PASSWORD variable : $KEY_PASSWORD"
        env:
          KEYSTORE_PASSWORD: ${{ vars.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
          KEY_PASSWORD: ${{ vars.KEY_PASSWORD }}
      

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2 # 3rd party tool
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck
