name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./app/build/outputs/apk/debug/app-debug.apk

      - name: Build test apk
        run: ./gradlew assembleDebugAndroidTest

      - name: Upload test apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-androidTest
          path: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: ./app/build/reports

  firebase_test:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Download app APK
        uses: actions/download-artifact@v3
        with:
          name: app-debug
          path: ./apks/app-debug.apk

      - name: Download Android test APK
        uses: actions/download-artifact@v3
        with:
          name: app-debug-androidTest
          path: ./apks/app-debug-androidTest.apk

      - id: 'auth'
        name: Login to Google CLoud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 465.0.0'

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app ./apks/app-debug.apk --test ./apks/app-debug-androidTest.apk --device model=b0q,version=33,locale=en,orientation=portrait